#!/usr/bin/env Rscript

# get command line arguments as an array
args <- commandArgs(trailingOnly = TRUE)

# if we don't have any command line arguments
# print out usage
if (length(args) == 0) {
        stop("Please provide a directory containing fast5 files as the first (and only) argument")
}

# the first argument is the directory, stop if it doesn't exist
my.dir <- args[1]
if (! file.exists(my.dir)) {
        stop(paste(my.dir, " does not exist"))
}

my.out <- args[2]
if (! exists("my.out")) {
	stop("please provide output file")
}

ncl <- args[3]
if (! exists("ncl")) {
	stop("please provide # of clusters")
}

ncl <- as.numeric(ncl)
if (ncl <= 0) {
	stop("# clusters must be greather than 0")
}

# get a list of all of the files with a .fast5 file name extension
f5files <- dir(path = my.dir, pattern = "\\.fast5$", full.names = TRUE)

# print to STDERR how many files we are going to attempt
write(paste("Extracting 2D fastq from", length(f5files), "files"), stderr())

# load poRe
suppressMessages(suppressWarnings(library(poRe)))
suppressMessages(suppressWarnings(library(parallel)))

printfastq <- function (f5, f5path = "/Analyses/Basecall_2D_000/BaseCalled_2D/")
{
    fid = tryCatch({
        H5Fopen(f5)
    }, warning = function(w) w, error = function(e) e)
    if (typeof(fid) == "S4" && H5Lexists(fid, f5path)) {
        did <- H5Dopen(fid, paste(f5path, "Fastq", sep = ""))
        fq <- (H5Dread(did))
        four <- strsplit(fq, "\n")[[1]]
        fq <- paste(paste(four[1], f5, sep = " "), four[2], four[3],
            four[4], sep = "\n")
        cat(fq, file = my.out, sep = "\n", fill = FALSE, append=TRUE)
        H5Dclose(did)
    }
    if (typeof(fid) == "S4") {
        H5Fclose(fid)
    }
}


cl <- makeCluster(ncl)
 
clusterExport(cl, "f5files")
c <- clusterEvalQ(cl, suppressWarnings(suppressMessages(library(poRe))))
clusterExport(cl, "my.out")
clusterExport(cl, "printfastq")


l <- parApply(cl, array(f5files), 1, printfastq)
stopCluster(cl)

# apply printfastq to every entry in f5files
# printfastq tests for 2D fastq and if found prints to STDOUT
#invisible(apply(array(f5files), 1, printfastq))
